type EnvKey =
  | "VITE_API_URL"
  | "VITE_TELEGRAM_BOT_USERNAME"
  | "VITE_GOOGLE_CLIENT_ID"
  | "VITE_GA_MEASUREMENT_ID"

const runtime = (window as unknown as { __ENV__?: Record<string, string> }).__ENV__ ?? {}

/**
 * Single point for reading env variables.
 * Prod: values from window.__ENV__ (env-config.js, generated by the container at startup).
 * Dev: fallback to import.meta.env (Vite reads .env at build/dev time).
 */
export function getEnv(key: EnvKey): string {
  return runtime[key] || (import.meta.env[key] as string)
}
