server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # env-config.js генерится при старте контейнера — не кэшируем
  location /env-config.js {
    add_header Cache-Control "no-store";
  }

  # SPA-fallback: все маршруты отдаём index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
